[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  DATABASE_URL = "postgresql://postgres.vtblcaqihlknddadycpr:82283703Lu!@aws-0-us-west-2.pooler.supabase.com:6543/postgres"

[context.production.environment]
  DATABASE_URL = "postgresql://postgres.vtblcaqihlknddadycpr:82283703Lu!@aws-0-us-west-2.pooler.supabase.com:6543/postgres"

[context.deploy-preview.environment]
  DATABASE_URL = "postgresql://postgres.vtblcaqihlknddadycpr:82283703Lu!@aws-0-us-west-2.pooler.supabase.com:6543/postgres"
